{{- if .Values.createSecretFromEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secret
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    reloader.stakater.com/match: "true"
  namespace: {{ .Release.Namespace }}
data:
{{- range $name, $value := .Values.secret }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}